# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 30
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 20

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40

 # [[main]]
  #  name = "Blog"
   #  url = "#blog"
   # weight =50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
# name = "Résumé"
#  url = "files/cv.pdf"
#  weight = 70

[[main]]
  name = "List 100"  # A link title for your page.
  url = "list/"  # The URL of your page.
  weight = 80  # The position of your page in the menu.

[[main]]
  name = "Resources"  # A link title for your page.
  url = "funres/"  # The URL of your page.
  weight = 85  # The position of your page in the menu.


  #[[main]]
  #name = "Reading List"  # A link title for your page.
  #url = "https://www.goodreads.com/rawslayn"  # The URL of your page.
  #weight = 90  # The position of your page in the menu.

  [[main]]
  name = "Contact"
  url = "#contact"
  weight = 95